name: Update Shipping Forecast

on:
  schedule:
    - cron: '0 5 * * *'  # Runs at 05:00 UTC daily.
  workflow_dispatch:  # This line enables manual triggering of the workflow.

jobs:
  update-forecast:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
      - name: Install dependencies
        run: gem install shipping-forecast
      - name: Generate Forecast Fragment
        run: ruby update_forecast.rb
      - name: Update index.html
        run: bash update_index.sh
      - name: Commit and Push Updates
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git add index.html
          git commit -m "Update Shipping Forecast" -a || exit 0
          git push
