# .github/workflows/scrape_and_update.yml
name: Scrape and Update Shipping Forecast

on:
  schedule:
    - cron: '0 5 * * *' # Runs every day at 05:00 UTC.
  workflow_dispatch: # Allows manual triggering from the GitHub UI.

jobs:
  scrape_and_update:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'

      - name: Install Nokogiri
        run: gem install nokogiri

      - name: Scrape Shipping Forecast
        run: ruby scrape_forecast.rb # Replace with the actual path to the script

      - name: Commit and push if changes
        run: |
          git config user.name "colechapman"
          git config user.email "cole.chapman15@gmail.com"
          git add data/shipping_forecast.txt
          git commit -m "Update Shipping Forecast data" -a || echo "No changes to commit"
          git push
